ALTER TABLE media
  ADD COLUMN IF NOT EXISTS branch_id INTEGER REFERENCES branches(id) ON DELETE CASCADE;

ALTER TABLE offers
  ALTER COLUMN branch_id DROP NOT NULL;

ALTER TABLE prices
  ALTER COLUMN branch_id DROP NOT NULL;
